// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xabW8bN/L/KgT/f6ApTs92k0bvHDttlMaOz7Fb9BLDoHZnJSZckiG5treGv/uBD/uk",
	"pWznkDoB7t5JWnJmOJz5zW9mdYMTkUvBgRuN5zdYJ2vIifv4Uimh7IcUdKKoNFRwPMcnv+yjZz9PniG7",
	"kVHCDQK7EinQUnANeIClEhKUoaD9fkMo60t6VeSEDxWQlCwZILiWjHBiHyItIaEZTZARyKypRiJJCqWA",
	"J1Y8XJNcMsBzfLoG9AMnOfyAMgosRVQjBZ8LqiBFy8KgK6IRFwZJJS5pCikeYFNKu1UbRfkK3w4w5doQ",
	"K7ln4dnJAinIwClGmVDemNo6f/Atto3dUz2eznZg96enz4bw8/PlcDpLd4Zk96enw93Z06fT3emz3clk",
	"ggc4EyonBs9xoeiwVhqzVxtiCh3x5+npMfIPUSLSjjW7k0ktiXIDK1BWlKGGRc79bi2UQevu/egiz4kq",
	"kciQWYP16JJB3jnygl8SRlO04LIwMdP9D3e7mabADc1KyldOkXey29nWtTZG6vl4nCb5KPw6SkReeZ16",
	"U4Y0mPJQ994OcBVAeP4eB7XeT+f1arH8CImxJ3oFhJl15DLc79V1aMpXDIzgNktEoZJ+lkgSE7NPuOA0",
	"IQzZ55XvW0JaDvGWWPtJ+pazEs+NKuBLAqhtc0R2GXVX1yUDfD0kIIe1if5oBhTX1qHByvMBlqxQhNXC",
	"rcLaTZXp9oeCEdU+XmUBqEuaQEhsNbJxQMU4LLOGHYdH/YP+UjBWQYKqvYkUSAUauHEg1LuhRAExcGFo",
	"HonhU5qDNiSX6GoNvMoQr8CCUEaVNkjBimoDygFRHZIpMTB0YiOXlVItGSkvLMrdi6FhMbKLA141dnRu",
	"9LdiCb9TZdA770d03Kzq2QA8lYJys8WT1WN0dvLGHl9B9/x7xwsLzCRJQGu6ZPFE1nLaSWQi6fhyOr7M",
	"N7I3CuFpBFU4/VzUcEJB1Q6JHLkx54vhuqDRqpKDISkxxBr2/woyPMf/N26K7ThU2nFlxGG1/naA43cd",
	"DuTuNgDBnSf5VCzhkioznM52Yhba2HaRHoGCN1Qbq6RZg3QhpVAG0lYhDOo3wfl9yBU8wCkwcB8KacPc",
	"Jj41kDuVW8oDJkqR0n6PY+JJla8OEpv77Ry+Cr4H19/7UdMf9iJew05L6W6ldon1T50BIstAdSHVxfWD",
	"ofnEAYcK7KgGaF7k1tsdWPGOTq2nG22dFT2tfst/iGyMaIMqpQ9DtY0i68K9hTIbvj7/0hrT3P1N9fGC",
	"predolOvwZ0qI/soGK8z9cJ2pbFZ03fgMVlRbr2DWMiqtvJujeFwbS4kWcGFEZ+AR27D/uwyUIFRFC4r",
	"mmR3IrvTKlCgC2a6AQfla/mv/cXTxceX5eHsbHJ0+ufOmz/Odt/+sTCHp68/HZbT9dHB2ezN6T/Lo49/",
	"Xh8dvNw5Oti7Otx//TwWNM0h5jdNTj8E6vqpfhthVj1gnN9gkqbUOoKw45bbfMJ2/bRXr0QVEiOyFIXZ",
	"LIld/9s8EfzC0eee738FsVJErmmC/DpHs2MVz8MmdC+g0EMg2gynMW9WsXyvEyv02yeSJNSUd6HGvutL",
	"TIPihFWMtGHx/cKxle0N8F+CRxyzd0koI0vKqCmRXYKEQtblCXADahtGNyuGywdQy9sB7h1+e3FIwhJE",
	"uYekGKUzwhB2kcgilmiGMLR/fIYSoUAj4s/YJS+zLW2VE5tDLlS5TbJ/GheLp6cvou2Tk8ujweml8iJf",
	"unqD7KpO/E3vslUbochqq9jweIu1s5i1/eu7db12JhyXFtyQxILl7WbmHuwf9niNo5BD1KmChKcoJ5ys",
	"IHcxnvV26dEHfmrrsCOg1li7UkeZU6DmQXbGxBUiGqWQUQ4poq7ufeDWNuBrwhOv1EaT0ISNPtjYYjQB",
	"rp0TPYPDe5Ika0CzkWUYhWItunt1dTUi7vFIqNU47NXjN4v9l0fvXg5no8lobXLWatNxzC14gC9Bae+7",
	"yylhck2mgd5xIime453RZLSLPZ1yYV91SfMbvAKztRFM1pB8crVm253gFotcpA4izaumD/UDIadyNplU",
	"9w6+kSBSMpq4reOPWvBm/HQfBL6qerxe7Lz9zQVeGFVsnMTGKFl1ulC7eNwpZFF/nIApFNeI1BW84VM1",
	"46vFoCtqW3UZADejzIDLiU1nWbpw3KYCRJEcjLPkfa/TcmJaWpblJv+mdt3nApSF7hCB4VHj2F6abio6",
	"JNc0L/IWlAQ2gaTVb1Eirion1566aPpXV2cKGSmYCRiUewXVN8rDtz469Y1r6I/0rMqjesycFou66/zn",
	"f2OgdnhhJFzfFa4lzgrWlGiburt32hAmb//4Mlv8ODdixAuSupkpaFdi67t6LP1nHK4lJJYfQ1jTzmDX",
	"iZLWvEa38rimL+eWkApttnVOoBBBHK562WqZim9eEOEIrqk2llELDqMPvFNvqLY8JpfC+mT+gQ/RIvPN",
	"eCrAT5nd9kHQ9O4YATeqtBt9O5y2N7m1ASs0yWHMRW3U4mDgR5/V/tBebduf0swNNE1HQreiEco0epII",
	"njGamB+DqGb9FoFW172iesi2787bmkrcCW1vK6isL2Vx4HK88XfHgi0J7+YwTTDeM6Hxie/C/oVIy6+e",
	"8z7UmzbXNim3j4A1sRSrS3aII/REwbDt0R9t5s8m08e1JmQFemLTpWfOo4Jg9ebCvy5w2p8/nvb9kEpo",
	"GKZ7qp2YhCkgqW1kUKHBGTebPZ5xv1vH+MyH6wRkVaS+t0LRAvrYTLtfMTrcrxkVLdJbX0Xc4DJST3Jx",
	"CYj0K0mmRB5ez7hQLnuweOBkPhQW+wPsjaYdGYHq+apDRDcwbRhQfSK8iURfDJQd1NqNDLkqm7xBKdI1",
	"t2HlN0vnxYEbWzMKqbdh9/FsqD1imUEmCp5+j1njQ7IVznfnzCDeIP0KJpYRyxJRo1HhA3lxEGsXv1o2",
	"PHIOPE7l/i46hP9l00OzyeeBvCeFLMXov93rNyGb+eTGWdCmBjS8jyFmjfJCG5QTk6w7Qlqbe+m3JyUr",
	"v2o5Cm/5/vZU/C/l7d9FUW1x5G8OAN+UpneJua12hAuzbk3pvkeMqoDmoSw5vPquQMFPscO/M7DNxrCp",
	"9yeyzXlxe1jf/PWgBw+4P/XrzKNje6t//Zzf/jsAAP//F15Dd9EoAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
