// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xa7XLbttK+FQzfd6btHH1bTVr9c223URo7Po7dTk/s8azIpYQEBBgAtM1mfO9nAPBT",
	"hGyl49ieM/knicDuYrH77LNLfQ5CkaSCI9cqmH0OVLjCBOzHAymFNB8iVKGkqaaCB7Pg5Nc98vKn0Uti",
	"NjIKXBM0K4lElQquMOgFqRQpSk1Ruf0aKOtKepUlwPsSIYIFQ4I3KQMO5iFRKYY0piHRgugVVUSEYSYl",
	"8tCIxxtIUobBLDhdIfmOQ4LfkZgiiwhVROKnjEqMyCLT5BoU4UKTVIorGmEU9AKdp2ar0pLyZXDbCyhX",
	"GozkjoVnJ3MiMUarmMRCOmMq69zBN9g2tE/VcDzZwemPL1728aefF/3xJNrpw/THF/3p5MWL8XT8cjoa",
	"jYJeEAuZgA5mQSZpv1Lqs1dp0Jny+PP09Ji4hyQUUcua6WhUSaJc4xKlEaWpZp5zv1sJqcmqfT8qSxKQ",
	"OREx0Ss0Hl0wTFpHnvMrYDQic55m2me6++FuN9MIuaZxTvnSKnJOtjubulZap2o2HEZhMih+HYQiKb1O",
	"nSl9WpiyrXtve0EZQMHsfVCodX66qFaLxQcMtTnRKwSmV57LsL+X16EoXzLUgpssEZkMu1mSgk/MHnDB",
	"aQiMmOel7xtCGg5xlhj7IXrLWR7MtMzwSwKoabNHdu51V9slveCmD5j2KxPd0TRKroxDCysvekHKMgms",
	"Em4UVm4qTTc/ZAxk83ilBSivaIhFYsuBiQMqhsUyY9hx8ah70F8zxkpIkJU3icRUokKuLQh1biiUCBov",
	"NU08MXxKE1QakpRcr5CXGeIUGBCKqVSaSFxSpVFaIKpCMgKNfSvWc1kRVSmD/NKg3L0YWiwmZnGBV7Ud",
	"rRv9PVvgH1Rq8s75kRzXqzo2II9SQbne4MnyMTk7eWOOL7F9/t3juQFmCENUii6YP5FVOm4lMqR0eDUe",
	"XiVr2euF8MiDKpx+yio4oSgrh3iOXJvzxXCdUW9VSVBDBBqMYf8vMQ5mwf8N62I7LCrtsDTisFx/2wv8",
	"d10cyN5tAQR3nuRjtsArKnV/PNnxWWhi20a6BwreUKWNknoNUVmaCqkxahTCQv06OL8vciXoBREytB+y",
	"1IS5SXyqMbEqN5SHAKSE3Hz3Y+JJma8WEuv7bR2+DL6t628XJd3hLv016zRP7S1ULjD+qCJexDFKC6E8",
	"S4w/bBSb612AZUih4Boot0YrLSQsbUUQkXFQfQq7rWOZc+U/BCIGShMnYVsQWquJNt5tiDaQYc1fF/fX",
	"BYPwDZQ2Edc9zTEsKTemElZEZHWxHXzmeKMvU1jipRYfkXtcY3620StRS4pXJcUwO4nZaRRIVBnT7fqH",
	"+ev0P3vzF/MPB/nh5Gx0dPrXzps/z6Zv/5zrw9PXHw/z8epo/2zy5vTf+dGHv26O9g92jvZ3rw/3Xv/s",
	"u8H6ELPPdT5sAxPdNLn1sJIOqHR8sRtF1HwERkqkIrAQmV4vGW0fmwIm+KWllx2Zv6FYSkhXNCRunaWh",
	"vorgYAXbTs5UH0Hp/tjnsTJu7nVUiQ57kEJIdX4X4dmzvF3XKAesZGw1y+0C60Y21Av+FtzjmN0roAwW",
	"lFGdE7OECEmMy0PkGuUmDKtX9BdbUK/GvZ9YnuHO5APQ+ilJIWcCHKhDBWcbA+AbHfmHdORtWgRYtjUv",
	"GZzzedxqX3tkf++QXFPGyBK5zSFiwgkyLRLQplFg+eCc/+8wmsE5P1MYEVAOqUGbroF8xNy6LQEdrgyM",
	"4w1V2nyQjeBW6674RomemBINzvkBhKtm89XAIrMeZcuHxQ0+PI1aIzUPzmdOynGY77Lskwp6ITZFwOuS",
	"Dv4+w07nSUMybTT52/KnTXSgVRfrKUgRe63evSTQrTBrrdiCQxcqto+tDrfZ7PWwWEIodxfoCyYtNLDL",
	"MM18XFkDI3vHZyQUEhUBR2HaxXKyYapoxSaYCJlvkuye+sUG49NfvNNDK5d7uaeTyrNkYbGGmFUtejm+",
	"y9YSOzaILR5vsHbis7bLzm7tqDkWdpRkcCs0BOa2t6bRFPj1tLWUpU9a8Qk8IglwWGJiKWzc2WXA9tRg",
	"sCU8xlizUnmBoY3DMRPXpuJGGFOOEaG2jzznxjbkK+ChU2qiSShgDqQZDbEAPFfug90UwhWSycCkbiZZ",
	"g15dX18PwD4eCLkcFnvV8M187+Do3UF/MhgNVjphjSl14HNL0AuuUCrnu6sxsHQF46KUc0hpMAt2BqPB",
	"NHA4ZcO+HBLOPgdL1BvnoOEKw48WSjfdSdBgDPPIdkD6VT2GdTBvVU5Go/Le0RFXSFNGQ7t1+EE5mu7A",
	"6j4oe1WOODux8/Z3G3jFpH7tJCZGYdkawprFw1Yv6vXHCepMckWgasJrpOt0DIpcU70ioqS7MWUabU6s",
	"O8sQquNmNw8SEtTWkvcdZm/FNLQs8nWuRc26TxnKvJxPzMr5fe3YTpquKzqEG5pkSQNKioGApSapYxg+",
	"VQncuOmDon97dVao01VaTyZSN/BwaO1T0xhw3HWui68YgK2RjScM32W2tYozVpNlk5LTO20oXij968ts",
	"cW8pPUb8ApF9FYjKdsYRxpAx/Xj6zzjepBia5gCLNc3MtN0ENF5DqEZ+VqTmwjAcofQmroKmZ+d43clC",
	"ImQx5CPA6+ZIcEOoT9Y4N40wSYXxyeyc94npOU1HFgl0L0/t9l6h6d0xQa5lbja6liZqbrJrCwxQkOCQ",
	"i8qo+X7PvdEr9xcsatP+iMb2PZ1uSWhXKqBMke9DwWNGQ/1DIapev0Gg0XWvqA5i7dnzNsj0nZBVdfzV",
	"pcz3bY7X/l7n+r6Ed1SxCsZ76LhLfBv2v4gof/Ccb02Wbtu0tmCpXx13qtbKk3ZVeS5ii3wvsd/08g8G",
	"DSaj8dNYVWQM+d6kUsesRwXI8mW9e0Nutf/8eNr3ijQj/WL8I5tJC0wiRKZ5IZnxaC+YTiaPZ9wfxjEO",
	"FfAmxLQsYM+tiDSKgG9u2q0mLb43/Fx5PLp1FcYOpjy1JhFX6JkOk1iKpPhHgg3lvAOZ+1bmtpDZnWSs",
	"zeGJFqSan1m0tNOHmh1VJwrWkemLQbSFYlPPu6nSJmdQRFTFe1j+ZOk837djSUYxcjZMH8+GyiOGNcQi",
	"49FzzBoXko1wvjtnev6m6DfUvoxY5IRqVQ755/u+FvHBsuGRc+DhK/mz7R6+ZdO22eTyIL0nhQzF6M6t",
	"uw3Kej7ZERY2qQEt/tMAekWSTGn3CqglpLG5k367acryBy1HxVucr56KX4/TPxWP34q/P4ui2uDITw4A",
	"T0rT28TcVDvgQq8ak7nniFEl0GzLkotXnSUouMl18Q+AwGRjsanzv+n1GXFzQF+/Wu7AQ9CdCLZm0L69",
	"5R9dL27/GwAA//8HlnBsxC8AAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
