// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xabW8bN/L/KgT/f6AtTs92k0bvHDttlMaOz7Fb9BLDoHZnJSZckiG5treGv/uBD/uk",
	"pWznkDgB7t5JWnJmOJz5zW9mdYMTkUvBgRuN5zdYJ2vIifv4Qimh7IcUdKKoNFRwPMcnv+6jp79MniK7",
	"kVHCDQK7EinQUnANeIClEhKUoaD9fkMo60t6WeSEDxWQlCwZILiWjHBiHyItIaEZTZARyKypRiJJCqWA",
	"J1Y8XJNcMsBzfLoG9AMnOfyAMgosRVQjBZ8KqiBFy8KgK6IRFwZJJS5pCikeYFNKu1UbRfkK3w4w5doQ",
	"K7ln4dnJAinIwClGmVDemNo6f/Atto3dUz2eznZg9+cnT4fwy7PlcDpLd4Zk9+cnw93ZkyfT3enT3clk",
	"ggc4EyonBs9xoeiwVhqzVxtiCh3x5+npMfIPUSLSjjW7k0ktiXIDK1BWlKGGRc79di2UQevu/egiz4kq",
	"kciQWYP16JJB3jnygl8SRlO04LIwMdP9D3e7mabADc1KyldOkXey29nWtTZG6vl4nCb5KPw6SkReeZ16",
	"U4Y0mPJQ994OcBVAeP4OB7XeT+f1arH8AImxJ3oJhJl15DLc79V1aMpXDIzgNktEoZJ+lkgSE7NPuOA0",
	"IQzZ55XvW0JaDvGWWPtJ+oazEs+NKuBzAqhtc0R2GXVX1yUDfD0kIIe1if5oBhTX1qHByvMBlqxQhNXC",
	"rcLaTZXp9oeCEdU+XmUBqEuaQEhsNbJxQMU4LLOGHYdH/YP+WjBWQYKqvYkUSAUauHEg1LuhRAExcGFo",
	"HonhU5qDNiSX6GoNvMoQr8CCUEaVNkjBimoDygFRHZIpMTB0YiOXlVItGSkvLMrdi6FhMbKLA141dnRu",
	"9PdiCX9QZdBb70d03Kzq2QA8lYJys8WT1WN0dvLaHl9B9/x7xwsLzCRJQGu6ZPFE1nLaSWQi6fhyOr7M",
	"N7I3CuFpBFU4/VTUcEJB1Q6JHLkx57PhuqDRqpKDISkxxBr2/woyPMf/N26K7ThU2nFlxGG1/naA43cd",
	"DuTuNgDBnSf5WCzhkioznM52Yhba2HaRHoGC11Qbq6RZg3QhpVAG0lYhDOo3wfldyBU8wCkwcB8KacPc",
	"Jj41kDuVW8oDJkqR0n6PY+JJla8OEpv77Ry+Cr4H19/7UdMf9iJew05L6W6ldon1T50BIstAdSHVxfWD",
	"ofnEAYcK7KgGaF7k1tsdWPGOTq2nG22dFT2tfst/iGyMaIMqpQ9DtY0i68K9hTIbvj6/v8bYK2shvo3e",
	"/kGOyYpyayViIbrrIOlhPYdrcyHJCi6M+Ag84hX7s8sEBUZRuKzoit2J7E6rQIEumOlePJSv5L/2F08W",
	"H16Uh7OzydHpXzuv/zzbffPnwhyevvp4WE7XRwdns9en/yyPPvx1fXTwYufoYO/qcP/Vs9jlNYeY3zS5",
	"9RDI6afcbYTh9ABqfoNJmlLrCMKOW27zidP10169ElWIiMhSFGazNHX9b+NV8AtHY3u+/w3EShG5pgny",
	"6xzdjVUeD1/QvYBCD4FoM5zGvFnF1L1OrFBon0iSUFPelb37rj8wDZoSVjHDhk33AXwr6xrgvwWPOGbv",
	"klBGlpRRUyK7BAmFrMsT4AbUNqxsVgyXD6B4twPcO/x2kE7CEkS5h4YYtTLCEHaRyCKWaIYwtH98hhKh",
	"QCPiz9glEbMt7Y0Tm0MuVLlNsn8aF4unp8+jbYyTy6PB6aXyIl863Ed2VSf+pnfZqo1QZLVVbHi8xdpZ",
	"zNr+9d26njcTjtMKbkhiwfJ2M3MP9g97/MJRuSHqVCPCU5QTTlaQuxjPerv06D0/tfXQEUFrrF2powwm",
	"UOQgO2PiChGNUsgohxRRV3/ec2sb8LXt2p1SG01CEzZ6b2OL0QS4dk70TArvSZKsAc1GttIXirVo59XV",
	"1Yi4xyOhVuOwV49fL/ZfHL19MZyNJqO1yVmrXcYxt+ABvgSlve8up4TJNZkGmsWJpHiOd0aT0S72tMaF",
	"fdWtzG/wCszWhixZQ/LR1Zptd4JbbG6ROog0L5t+0A9mnMrZZFLdO3hCT6RkNHFbxx+04M0Y6D4IfFn1",
	"Wr3YefO7C7wwMtg4iY1Rsup0g3bxuFPIov44AVMorhGpK3jDa2rmVYtBV9S2zDIAbkaZAZcTm86ydOG4",
	"TQWIIjkYZ8m7XsfjxLS0LMtNHkztuk8FKAvdIQLDo8axvTTdVHRIrmle5C0oCWwCSavfokRcVU6uPXXR",
	"9O+uzhQyUjATMCj3CqpvlIdvfXTqG9fQH+lZlUf1mDktFnXX+c+/YqB2eGEkXN8WrjXNCtaUaJu6u3fa",
	"ECZg//g8W/xYNWLEc5K62SVoV2Lru3os/WccriUklh9DWNPOYNcRktbcRLfyuKYv55aQCm22dTCgEEEc",
	"rnrZapmKbyIQ4QiuqTaWUQsOo/e8U2+otjwml8L6ZP6eD9Ei801xKsBPe932QdD09hgBN6q0G31bmrY3",
	"ubUBKzTJYcxFbdTiYOBHkNX+0OZs25/SzA0WTUdCt6IRyjT6MRE8YzQxPwVRzfotAq2ue0X1kG3fnbc1",
	"HbgT2t5UUFlfyuLA5Xjj744FWxLezUOaYLxnUuIT34X9c5GWXzznfag37WZoFb861sRSrC7ZIY7QjwqG",
	"bY/+ZDN/Npk+rjUhK9CPNl165jwqCFZvEPzY3ml/9nja90MqoWGYsql2YhKmgKS2kUGFBmfcbPZ4xv1h",
	"HeMzH64TkFWR+t4KRQvoY7PlfsXocL/xTe3x9NZXETdAjNSTXFwCIv1KkimRh9ckLpTLHiweOJkPhcX+",
	"IHmjaUdGoHrO6RDRDS4bBlSfCG8i0WcDZQe1diNDrsomb1CKdM1tWPnN0nlx4MbHjELqbdh9PBtqj1hm",
	"kImCp99j1viQbIXz3TkziDdIv4GJZcSyRNRoVPhAXhzE2sUvlg2PnAOPU7m/iw7hf9n00GzyeSDvSSFL",
	"Mfpv2fpNyGY+uXEWtKkBDe9FiFmjvNAG5cQk646Q1uZe+u1JycovWo7C27avnor/pbz9uyiqLY78zQHg",
	"m9L0LjG31Y5wYdatKd33iFEV0DyUJYdX0BUo+Cl2+JcEttkYNvX+zLU5L24P65u/APTgAfenfp15dGxv",
	"9e+b89t/BwAA//9bJ3e/WSgAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
